var nodemailer = require('nodemailer');
require('dotenv').config();
// email sender function
exports.sendEmail = function (email, token) {
    // Definimos el transporter
    var transporter = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
            user: process.env.MAILTRAP_USER, //generated by Mailtrap
            pass: process.env.MAILTRAP_PASS //generated by Mailtrap
        }
    });
    // Definimos el email
    var mailOptions = {
        from: 'Tienda de Colchones',
        to: email,
        subject: 'Password recovery',
        html: `<b>Click the link to reset your password.<b/><br> <a href="localhost:4000/reset-password/${token}">Recover password</a>`
    };
    // Enviamos el email
    transporter.sendMail(mailOptions, function (error, info) {
        if (error) {
            console.log(error);
            res.send(500, err.message);
        } else {
            console.log("Email sent");
            res.status(200).jsonp(req.body);
        }
    });
};